---
abstract: 'RT-Extension-AssetAutoName Extension'
author:
  - 'Andrew Ruthven, Catalyst Cloud Ltd <puck@catalystcloud.nz>'
build_requires:
  ExtUtils::MakeMaker: 6.59
configure_requires:
  ExtUtils::MakeMaker: 6.59
distribution_type: module
dynamic_config: 1
generated_by: 'Module::Install version 1.19'
license: gpl_2
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: RT-Extension-AssetAutoName
no_index:
  directory:
    - inc
requires:
  perl: 5.10.1
resources:
  license: http://opensource.org/licenses/gpl-license.php
  repository: https://github.com/catalyst-cloud/rt-extension-assetautoname
version: '0.05'
x_module_install_rtx_version: '0.40'
x_requires_rt: 4.4.0
